apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-tareas
  namespace: tasks-namespace

spec:
  selector:
    matchLabels:
      app: frontend-tareas
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-tareas
    spec:
      
      containers:
        - name: frontend-tareas
          image: loliconario69/laravel:v3
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: configuracion-de-frontend
          volumeMounts:
            - mountPath: /app
              name: project
      volumes:
        - name: project
          hostPath: 
            path: /root/frontend-tareas
            type: Directory

---
