apiVersion: v1
kind: Service
metadata:
  name: frontend-tareas
  namespace: tasks-namespace
spec:
  type: NodePort
  selector:
    app: frontend-tareas
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30303
---


